name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # Common Linux dependencies
    - name: Install common Linux Dependencies
      if: runner.os == 'Linux'
      uses: ./.github/actions/install-linux-deps

    - name: Install Linux GUI & SFML dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update

        # Build tools
        sudo apt-get install -y ninja-build xdotool openbox

        # === REQUIRED for SFML (X11) ===
        sudo apt-get install -y \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libudev-dev

        # === SFML text & audio ===
        sudo apt-get install -y \
          libfreetype6-dev \
          libopenal-dev \
          libvorbis-dev \
          libflac-dev

        # XCB (optional, but nice to have)
        sudo apt-get install -y \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          libxcb1-dev \
          libxcb-icccm4-dev \
          libxcb-image0-dev \
          libxcb-keysyms1-dev \
          libxcb-randr0-dev \
          libxcb-render-util0-dev \
          libxcb-xinerama0-dev \
          libxcb-xfixes0-dev

        # https://github.com/llvm/llvm-project/issues/78354
        sudo sysctl vm.mmap_rnd_bits=28

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        sudo apt-get install --no-install-recommends valgrind
